import { Theme } from '@/constants/Theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Theme.colors.background,
    },
    scrollView: {
        flex: 1,
    },
    header: {
        paddingTop: Theme.spacing.md,
        paddingHorizontal: Theme.spacing.lg,
        paddingBottom: Theme.spacing.md,
        borderBottomWidth: 0,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
    },
    headerButton: {
        padding: Theme.spacing.sm,
        borderRadius: Theme.borderRadius.full,
    },
    debitCardContainer: {
        padding: Theme.spacing.lg,
    },
    debitCard: {
        backgroundColor: Theme.colors.primary,
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: Theme.colors.textSecondary,
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 8,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.xl,
    },
    cardChip: {
        width: 40,
        height: 30,
        backgroundColor: Theme.colors.surface + '40',
        borderRadius: Theme.borderRadius.sm,
    },
    cardBalance: {
        fontSize: 32,
        fontWeight: '700',
        color: Theme.colors.surface,
        marginBottom: Theme.spacing.md,
    },
    cardDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    cardLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: Theme.colors.surface + '90',
        marginBottom: 4,
    },
    cardSubtext: {
        fontSize: 14,
        color: Theme.colors.surface,
        fontWeight: '500',
    },
    cardLogo: {
        opacity: 0.9,
    },
    balanceDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        ...Theme.shadows.small,
    },
    balanceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.sm,
    },
    balanceIcon: {
        width: 36,
        height: 36,
        borderRadius: Theme.borderRadius.full,
        justifyContent: 'center',
        alignItems: 'center',
    },
    incomeIcon: {
        backgroundColor: Theme.colors.success + '20',
    },
    expenseIcon: {
        backgroundColor: Theme.colors.error + '20',
    },
    balanceLabel: {
        fontSize: 12,
        color: Theme.colors.textSecondary,
        marginBottom: 2,
    },
    balanceAmount: {
        fontSize: 16,
        fontWeight: '600',
    },
    incomeText: {
        color: Theme.colors.success,
    },
    expenseText: {
        color: Theme.colors.error,
    },
    miniCalendar: {
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginHorizontal: Theme.spacing.lg,
        marginBottom: Theme.spacing.lg,
        ...Theme.shadows.small,
    },
    calendarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.md,
    },
    calendarTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
    },
    weekDays: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: Theme.spacing.sm,
    },
    weekDayText: {
        fontSize: 12,
        color: Theme.colors.textSecondary,
        width: 32,
        textAlign: 'center',
    },
    calendarDays: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
    },
    calendarDay: {
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 2,
    },
    selectedDay: {
        backgroundColor: Theme.colors.primary,
        borderRadius: Theme.borderRadius.full,
    },
    calendarDayText: {
        fontSize: 14,
        color: Theme.colors.textPrimary,
    },
    selectedDayText: {
        color: Theme.colors.surface,
        fontWeight: '600',
    },
    transactionDots: {
        flexDirection: 'row',
        gap: 2,
        position: 'absolute',
        bottom: 2,
    },
    transactionDot: {
        width: 4,
        height: 4,
        borderRadius: 2,
    },
    budgetSection: {
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginHorizontal: Theme.spacing.lg,
        marginBottom: Theme.spacing.lg,
        ...Theme.shadows.small,
    },
    budgetMonth: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
        fontWeight: '500',
    },
    budgetCards: {
        gap: Theme.spacing.md,
        marginTop: Theme.spacing.md,
    },
    budgetCard: {
        backgroundColor: Theme.colors.surfaceHighlight,
        borderRadius: Theme.borderRadius.md,
        padding: Theme.spacing.md,
    },
    budgetCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.sm,
    },
    categoryInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.sm,
    },
    categoryIcon: {
        width: 36,
        height: 36,
        borderRadius: Theme.borderRadius.full,
        justifyContent: 'center',
        alignItems: 'center',
    },
    categoryName: {
        fontSize: 16,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: 2,
    },
    budgetAmount: {
        fontSize: 13,
        color: Theme.colors.textSecondary,
    },
    percentageText: {
        fontSize: 16,
        fontWeight: '600',
        color: Theme.colors.primary,
    },
    overBudget: {
        color: Theme.colors.error,
    },
    progressBarContainer: {
        height: 4,
        backgroundColor: Theme.colors.border,
        borderRadius: Theme.borderRadius.full,
        overflow: 'hidden',
        marginTop: Theme.spacing.sm,
    },
    progressBar: {
        height: '100%',
        borderRadius: Theme.borderRadius.full,
    },
    viewAllBudgets: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Theme.spacing.xs,
        marginTop: Theme.spacing.lg,
        paddingVertical: Theme.spacing.sm,
        borderTopWidth: 1,
        borderTopColor: Theme.colors.border,
    },
    viewAllBudgetsText: {
        fontSize: 14,
        color: Theme.colors.primary,
        fontWeight: '500',
    },
    recentActivity: {
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginHorizontal: Theme.spacing.lg,
        marginBottom: Theme.spacing.lg,
        ...Theme.shadows.small,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.md,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
    },
    viewAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.xs,
    },
    viewAllText: {
        fontSize: 14,
        color: Theme.colors.primary,
        fontWeight: '500',
    },
    transactionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: Theme.spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.border,
    },
    transactionIcon: {
        marginRight: Theme.spacing.md,
    },
    transactionInfo: {
        flex: 1,
    },
    transactionCategory: {
        fontSize: 16,
        fontWeight: '500',
        color: Theme.colors.textPrimary,
        marginBottom: 2,
    },
    transactionDate: {
        fontSize: 12,
        color: Theme.colors.textSecondary,
    },
    transactionAmount: {
        fontSize: 16,
        fontWeight: '600',
    },
    emptyContainer: {
        alignItems: 'center',
        padding: Theme.spacing.xl,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginTop: Theme.spacing.md,
    },
    emptySubText: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
        marginTop: Theme.spacing.xs,
    },
    fab: {
        position: 'absolute',
        right: Theme.spacing.lg,
        bottom: Theme.spacing.lg,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: Theme.colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        ...Theme.shadows.medium,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalOverlayTouch: {
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: Theme.colors.background,
        borderRadius: 16,
        padding: 16,
        width: '90%',
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.lg,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
    },
    closeButton: {
        padding: Theme.spacing.xs,
    },
    input: {
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginBottom: Theme.spacing.md,
        fontSize: 16,
        color: Theme.colors.textPrimary,
        borderWidth: 1,
        borderColor: Theme.colors.border,
    },
    descriptionInput: {
        height: 100,
        textAlignVertical: 'top',
    },
    addButton: {
        padding: Theme.spacing.lg,
        borderRadius: Theme.borderRadius.lg,
        alignItems: 'center',
        marginTop: Theme.spacing.md,
    },
    addButtonText: {
        color: Theme.colors.background,
        fontSize: 16,
        fontWeight: '600',
    },
    settingsButton: {
        padding: Theme.spacing.sm,
    },
    settingsSection: {
        marginTop: Theme.spacing.lg,
    },
    settingsSectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: Theme.spacing.md,
    },
    categoryTypeSelector: {
        flexDirection: 'row',
        marginBottom: Theme.spacing.md,
    },
    categoryTypeButton: {
        flex: 1,
        paddingVertical: Theme.spacing.sm,
        paddingHorizontal: Theme.spacing.md,
        marginHorizontal: Theme.spacing.xs,
        borderRadius: Theme.borderRadius.full,
        backgroundColor: Theme.colors.surface,
        alignItems: 'center',
    },
    categoryTypeButtonActive: {
        backgroundColor: Theme.colors.primary,
    },
    categoryTypeText: {
        color: Theme.colors.textSecondary,
        fontSize: 14,
    },
    categoryTypeTextActive: {
        color: Theme.colors.background,
        fontWeight: '600',
    },
    addCategoryContainer: {
        flexDirection: 'row',
        marginBottom: Theme.spacing.lg,
    },
    categoryInput: {
        flex: 1,
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.md,
        marginRight: Theme.spacing.sm,
        fontSize: 16,
        color: Theme.colors.textPrimary,
        borderWidth: 1,
        borderColor: Theme.colors.border,
    },
    addCategoryButton: {
        backgroundColor: Theme.colors.primary,
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    categoryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Theme.colors.surface,
        padding: Theme.spacing.md,
        borderRadius: Theme.borderRadius.lg,
        marginBottom: Theme.spacing.sm,
    },
    deleteCategoryButton: {
        padding: Theme.spacing.xs,
    },
    emptyCategoriesText: {
        textAlign: 'center',
        color: Theme.colors.textSecondary,
        marginTop: Theme.spacing.xl,
    },
    categorySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginBottom: Theme.spacing.md,
        borderWidth: 1,
        borderColor: Theme.colors.border,
    },
    categoryText: {
        flex: 1,
        fontSize: 16,
        color: Theme.colors.textPrimary,
    },
    placeholderText: {
        flex: 1,
        fontSize: 16,
        color: Theme.colors.textSecondary,
    },
    categoryPickerItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: Theme.spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.border,
    },
    categoryPickerText: {
        fontSize: 16,
        color: Theme.colors.textPrimary,
    },
    categoryPickerTextSelected: {
        color: Theme.colors.primary,
        fontWeight: '600',
    },
    noCategoriesContainer: {
        padding: Theme.spacing.xl,
        alignItems: 'center',
    },
    noCategoriesText: {
        fontSize: 16,
        color: Theme.colors.textSecondary,
        textAlign: 'center',
        marginBottom: Theme.spacing.lg,
    },
    addCategoryFromPickerButton: {
        backgroundColor: Theme.colors.primary,
        paddingHorizontal: Theme.spacing.xl,
        paddingVertical: Theme.spacing.lg,
        borderRadius: Theme.borderRadius.lg,
    },
    addCategoryFromPickerText: {
        color: Theme.colors.background,
        fontSize: 16,
        fontWeight: '600',
    },
    datePickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Theme.colors.surface,
        borderRadius: Theme.borderRadius.lg,
        padding: Theme.spacing.lg,
        marginBottom: Theme.spacing.md,
        borderWidth: 1,
        borderColor: Theme.colors.border,
    },
    datePickerButtonText: {
        fontSize: 16,
        color: Theme.colors.textPrimary,
        marginLeft: Theme.spacing.md,
    },
    transactionDetails: {
        marginTop: Theme.spacing.lg,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: Theme.spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.border,
    },
    detailLabel: {
        fontSize: 16,
        color: Theme.colors.textSecondary,
    },
    detailValue: {
        fontSize: 16,
        color: Theme.colors.textPrimary,
        fontWeight: '500',
    },
    typeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    typeIcon: {
        marginRight: Theme.spacing.xs,
    },
    typeText: {
        fontSize: 16,
        fontWeight: '500',
    },
    descriptionContainer: {
        marginTop: Theme.spacing.lg,
    },
    descriptionText: {
        fontSize: 16,
        color: Theme.colors.textPrimary,
        marginTop: Theme.spacing.sm,
        lineHeight: 24,
    },
    quickActions: {
        flexDirection: 'row',
        marginBottom: 16,
    },
    actionButton: {
        alignItems: 'center',
        backgroundColor: Theme.colors.surface,
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        gap: 12,
    },
    actionIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionText: {
        fontSize: 16,
        fontWeight: '500',
        color: Theme.colors.textPrimary,
    },
    budgetOverview: {
        gap: 12,
    },
    insightCard: {
        backgroundColor: Theme.colors.surface,
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
    },
    insightTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: 16,
    },
    insightRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    insightItem: {
        flex: 1,
    },
    insightLabel: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
        marginBottom: 4,
    },
    insightValue: {
        fontSize: 24,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: 4,
    },
    insightChange: {
        fontSize: 14,
        fontWeight: '500',
    },
    insightSubtext: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
    },
    insightDivider: {
        width: 1,
        height: 40,
        backgroundColor: Theme.colors.border,
        marginHorizontal: 20,
    },
    patternList: {
        gap: 12,
    },
    patternItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    patternRank: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: Theme.colors.primary + '20',
        justifyContent: 'center',
        alignItems: 'center',
    },
    patternRankText: {
        fontSize: 14,
        fontWeight: '600',
        color: Theme.colors.primary,
    },
    patternInfo: {
        flex: 1,
    },
    patternCategory: {
        fontSize: 16,
        fontWeight: '500',
        color: Theme.colors.textPrimary,
        marginBottom: 2,
    },
    patternAmount: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
    },
    patternPercentage: {
        fontSize: 14,
        fontWeight: '500',
        color: Theme.colors.textPrimary,
    },
    budgetTitleSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.sm,
    },
    priorityIndicator: {
        width: 36,
        height: 36,
        borderRadius: Theme.borderRadius.full,
        justifyContent: 'center',
        alignItems: 'center',
    },
    budgetTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: 2,
    },
    budgetCategory: {
        fontSize: 13,
        color: Theme.colors.textSecondary,
    },
    daysRemaining: {
        fontSize: 13,
        color: Theme.colors.textSecondary,
        fontWeight: '500',
    },
    overdue: {
        color: Theme.colors.error,
    },
    urgent: {
        color: Theme.colors.warning,
    },
    budgetProgress: {
        marginTop: Theme.spacing.sm,
    },
    progressInfo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.xs,
    },
    progressAmount: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
    },
    completed: {
        color: Theme.colors.success,
    },
    emptyBudgets: {
        alignItems: 'center',
        padding: Theme.spacing.lg,
    },
    emptyBudgetsText: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
        marginBottom: Theme.spacing.md,
    },
    addBudgetButton: {
        backgroundColor: Theme.colors.primary + '10',
        paddingVertical: Theme.spacing.sm,
        paddingHorizontal: Theme.spacing.md,
        borderRadius: Theme.borderRadius.full,
    },
    addBudgetText: {
        fontSize: 14,
        color: Theme.colors.primary,
        fontWeight: '500',
    },
    budgetAllocationContainer: {
        marginTop: 12,
        marginBottom: 16,
    },
    budgetAllocationBar: {
        height: 4,
        backgroundColor: Theme.colors.surface + '40',
        borderRadius: 2,
        overflow: 'hidden',
        marginBottom: 8,
    },
    budgetAllocationFill: {
        height: '100%',
        backgroundColor: Theme.colors.surface,
        borderRadius: 2,
    },
    budgetAllocationLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    budgetAllocationText: {
        color: Theme.colors.surface,
        fontSize: 12,
        fontWeight: '500',
    },
    createBudgetPrompt: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: Theme.colors.surface,
        padding: 16,
        borderRadius: 12,
        marginTop: 8,
    },
    createBudgetText: {
        color: Theme.colors.primary,
        fontSize: 14,
        fontWeight: '600',
    },
    typePickerContent: {
        padding: 0,
        overflow: 'hidden',
    },
    typeOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.border,
    },
    selectedTypeOption: {
        backgroundColor: Theme.colors.surface,
        borderRadius: 12,
        margin: 8,
        marginHorizontal: 12,
        borderBottomWidth: 0,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    incomeOption: {
        backgroundColor: Theme.colors.success + '10',
    },
    expenseOption: {
        backgroundColor: Theme.colors.error + '10',
    },
    typeIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Theme.colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    selectedTypeIconContainer: {
        transform: [{ scale: 1.1 }],
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    typeTextContainer: {
        flex: 1,
    },
    typeTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: Theme.colors.textPrimary,
        marginBottom: 4,
    },
    selectedTypeTitle: {
        transform: [{ scale: 1.05 }],
    },
    typeDescription: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
    },
    selectedTypeDescription: {
        opacity: 0.8,
    },
    typeArrow: {
        opacity: 0.7,
    },
    dayTransactionsSummary: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: Theme.colors.surface,
        borderRadius: 12,
        marginBottom: 15,
    },
    summaryItem: {
        flex: 1,
        alignItems: 'center',
    },
    summaryLabel: {
        fontSize: 14,
        color: Theme.colors.textSecondary,
        marginBottom: 4,
    },
    summaryAmount: {
        fontSize: 18,
        fontWeight: '600',
    },
    summaryDivider: {
        width: 1,
        height: '80%',
        backgroundColor: Theme.colors.border,
        marginHorizontal: 15,
    },
    emptyDayContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    emptyDayText: {
        fontSize: 16,
        color: Theme.colors.textSecondary,
        marginTop: 10,
    },
    dayTransactionsList: {
        flexGrow: 1,
    },
    dayAmount: {
        fontSize: 12,
        fontWeight: '500',
        marginTop: 2,
    },
    cloudModal: {
        maxHeight: '80%',
        backgroundColor: Theme.colors.surface,
        borderRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 20,
        marginHorizontal: 15,
        shadowColor: Theme.colors.textPrimary,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 5,
    },
    cloudPointer: {
        position: 'absolute',
        top: -10,
        left: '50%',
        marginLeft: -10,
        width: 20,
        height: 20,
        backgroundColor: Theme.colors.surface,
        transform: [{ rotate: '45deg' }],
        shadowColor: Theme.colors.textPrimary,
        shadowOffset: {
            width: -1,
            height: -1,
        },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
}); 